version: '3'

services:
  caddy:
    image: caddy:latest
    container_name: matrixdl-caddy
    ports:
      - "80:80"
    volumes:
      - ./caddy/data:/data  # TODO: use docker volume
      - ./caddy/config:/etc/caddy
    networks:
      - matrixdl

  frontend:
    image: ghcr.io/sysumatrixdl/frontend:latest
    container_name: frontend
    networks:
      - matrixdl
    environment:
      - "BACKEND_SUFFIX=http://backend:8000"

  backend:
    image: ghcr.io/sysumatrixdl/backend:latest
    container_name: backend
    volumes:
      - ./backend:/app/tmp
    environment:
      - "BACKEND_HOST=backend"
      - "BACKEND_PORT=8000"
      - "MATRIXDL_ENVIROMENT=PRODUCTION"
      # - "MATRIXDL_WORKER=4"
    networks:
      - matrixdl
    depends_on:
      - open-gauss

  open-gauss:
    image: ghcr.io/sysumatrixdl/opengauss:latest
    container_name: open-gauss
    ports:
      - "5432:5432"  # TODO: use sqlpad instead of expose port here
    volumes:
      - ./data:/opt/openGauss/data  # TODO: use docker volume
    networks:
      - matrixdl

  grafana:
    image: ghcr.io/sysumatrixdl/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
    depends_on:
      - open-gauss
    networks:
      - matrixdl
    links:
      - open-gauss

networks:
  matrixdl:
    driver: bridge
    ipam:
      # 避免和校园网网段(172.12.0.0/16)冲突
      driver: default
      config:
        - subnet: 192.168.114.0/24
          gateway: 192.168.114.254