apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          env:
            - name: BACKEND_HOST
              value: {{ .Values.backend.host }}
            - name: BACKEND_PORT
              value: {{ .Values.backend.port }}
            - name: MATRIXDL_ENVIROMENT
              value: {{ .Values.backend.enviroment }}
            - name: MATRIXDL_WORKER
              value: {{ .Values.backend.worker }}